/*
 * Oodle Alerts API
 *
 * API of the Oodle Alert management.
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	sw "alerts_mock/go"

	"github.com/gorilla/handlers"
)

func main() {
	log.Printf("Server started")

	router := sw.NewRouter()
	// Handle OPTIONS requests
	router.HandleFunc("/", testHandler).Methods("GET")
	http.ListenAndServe(":8080",
		handlers.CORS(
			handlers.AllowedOrigins([]string{"http://localhost:3000"}),
			handlers.AllowedMethods([]string{"GET", "POST", "PUT", "DELETE", "OPTIONS"}),
			handlers.AllowedHeaders([]string{"X-Requested-With", "Content-Type", "Authorization"}),
		)(router))

	log.Fatal(http.ListenAndServe(":8080", router))
}

func testHandler(w http.ResponseWriter, r *http.Request) {

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write([]byte(`("message": "Hello World!")`))
}
