/*
 * Oodle Alerts API
 *
 * API of the Oodle Alert management.
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The annotations clause specifies a set of informational labels that can be used to store longer additional information such as alert descriptions or runbook links
type Annotation struct {
	// Name of the annotation
	Name string `json:"name,omitempty"`
	// Value for the annotation
	Value string `json:"value,omitempty"`
}
