/*
 * Oodle Alerts API
 *
 * API of the Oodle Alert management.
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// The labels clause allows specifying a set of additional labels to be attached to the alert. Any existing conflicting labels will be overwritten
type Label struct {
	// Name of the label
	Name string `json:"name,omitempty"`
	// Value for the label
	Value string `json:"value,omitempty"`
}
