/*
 * Oodle Alerts API
 *
 * API of the Oodle Alert management.
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Alert struct {
	// uuid to identify the alert
	Id string `json:"id,omitempty"`
	// name of the alert derived from the alert rule
	Name string `json:"name,omitempty"`
	// The alert-rule expression evaluated to create the alert
	Expression *interface{} `json:"expression,omitempty"`
	// The time the alert started at
	StartsAt time.Time `json:"startsAt,omitempty"`
	// The time the alert was last updated at
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
	// The time the alert ends at
	EndsAt time.Time `json:"endsAt,omitempty"`
	// Normal - The state of an alert that is neither firing nor pending. Pending - The state of an alert that has been active for less than the configured threshold duration. Alerting - The state of an alert that has been active for longer than the configured threshold duration.
	Status string `json:"status,omitempty"`

	Labels *[]Label `json:"labels,omitempty"`

	Annotations *[]Annotation `json:"annotations,omitempty"`

	AlertRuleUUID string `json:"alertRuleUUID,omitempty"`
}
