/*
 * Oodle Alerts API
 *
 * API of the Oodle Alert management.
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"ClearPost",
		strings.ToUpper("Post"),
		"/clear",
		ClearPost,
	},

	Route{
		"AlertRulePost",
		strings.ToUpper("Post"),
		"/alert-rule",
		AlertRulePost,
	},

	Route{
		"AlertRuleUuidGet",
		strings.ToUpper("Get"),
		"/alert-rule/{uuid}",
		AlertRuleUuidGet,
	},

	Route{
		"AlertRuleUuidPut",
		strings.ToUpper("Put"),
		"/alert-rule/{uuid}",
		AlertRuleUuidPut,
	},

	Route{
		"AlertRulesGet",
		strings.ToUpper("Get"),
		"/alert-rules",
		AlertRulesGet,
	},

	Route{
		"AlertUuidGet",
		strings.ToUpper("Get"),
		"/alert/{uuid}",
		AlertUuidGet,
	},

	Route{
		"AlertsGet",
		strings.ToUpper("Get"),
		"/alerts",
		AlertsGet,
	},
}
